import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from collections import Counter

# Summary for Base Type, Semantic Type and Validity

'''
This part is the summary based off the output generated by the pyspark program.
To run this program bug-free, please run the pyspark program first. When the output files are ready, please change the variable "filename" according to the directory where the file is saved.
'''

colnames = ['CMPLNT_NUM', 'CMPLNT_FR_DT', 'CMPLNT_FR_TM', 'CMPLNT_TO_DT',
            'CMPLNT_TO_TM', 'RPT_DT', 'KY_CD', 'OFNS_DESC', 'PD_CD', 'PD_DESC',
            'CRM_ATPT_CPTD_CD', 'LAW_CAT_CD', 'JURIS_DESC', 'BORO_NM',
            'ADDR_PCT_CD', 'LOC_OF_OCCUR_DESC', 'PREM_TYP_DESC', 'PARKS_NM',
            'HADEVELOPT', 'X_COORD_CD', 'Y_COORD_CD', 'Latitude', 'Longitude',
            'Lat_Lon']

df_summary = pd.DataFrame(
    columns=['Column Name', 'Base Type Count', 'Semantic Type Count', 'Validity Count'])
df_summary['Column Name'] = colnames

for i in range(24):
    filename = "result/column{0}_summary.csv".format(str(i))
    df = pd.read_csv(filename, header=None, names=[
                     colnames[i], 'Base Type', 'Semantic Type', 'Validity'])
    df = df.fillna('Null')
    for j in range(1, 4):
        cnt = Counter()
        for value in df[df.columns[j]]:
            cnt[value] += 1
        df_summary.ix[i, j] = ', '.join("{!s}: {!r}".format(
            key, val) for (key, val) in cnt.items())

print(df_summary)
